name: CI/CD with Terraform

on:
  push:
    branches:
      - main
      - Complete-CI-CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_REGION: ap-south-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug repo structure (DO NOT REMOVE YET)
      run: |
        echo "PWD:"
        pwd
        echo "ROOT FILES:"
        ls -la
        echo "TERRAFORM FOLDER:"
        ls -la terraform || echo "terraform folder NOT FOUND"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        terraform -chdir=terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET_NAME}" \
          -backend-config="region=${AWS_REGION}"

    - name: Terraform Validate
      run: terraform -chdir=terraform validate

    - name: Terraform Plan
      run: |
        terraform -chdir=terraform plan \
          -var="region=${AWS_REGION}" \
          -var="key_name=deployer"

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
